# Generated by Django 4.1.7 on 2023-03-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="description",
            new_name="details",
        ),
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
