# Generated by Django 4.1.7 on 2023-03-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_rename_description_event_details_event_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
