# Generated by Django 4.1.7 on 2023-03-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_alter_event_category_alter_event_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="event",
            name="longitude",
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
