# Generated by Django 4.1.7 on 2023-03-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0005_remove_event_latitude_remove_event_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="event_pics"),
        ),
    ]
