# Generated by Django 4.1.7 on 2023-03-15 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0006_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True, related_name="attendees", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
